import type { GetStaticProps, GetStaticPropsResult, NextPage } from 'next'
import Head from 'next/head'
import PokemonPage from '../../src/pages/PokemonPage'
import api from '../../src/services/api'

interface Props{
  pokemon: {
    id: string;
    name: string;
    types: {
      type: {
        name: string
      }
    }[]
    height: number;
    weight: number;
  }
}

export const getStaticPaths = async() => {
  const maxPokemons = 252
  const res = await api.get(`/?limit=${maxPokemons}`)

  const paths = res.data.results.map((item: any, index: any) => {
    return {
      params: { id: (index + 1).toString() }
    }
  })

  return {
    paths,
    fallback: false,
  }
}

export const getStaticProps = async(context: any) => {
  const id = context.params.id

  const res = await api.get(`/${id}`)

  return {
    props: { pokemon: res.data }
  }
}

const Pokemon: NextPage<Props> = ({ pokemon }) => {
  return (
    <>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PokemonPage pokemon={pokemon} />
    </>
  )
}

export default Pokemon
